---
name: data-pulse
services:
  db:
    image: mariadb:11.6.2-noble
    restart: unless-stopped
    container_name: db
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ALLOW_EMPTY_PASSWORD: no
    ports:
      - 3307:3306
    volumes:
      - db-data-pulse:/var/lib/mysql
    networks:
      - data-pulse
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 3001:3000
    networks:
      - data-pulse
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: client
    depends_on:
      db:
        condition: service_started
      api:
        condition: service_started
    ports:
      - 81:80
    networks:
      - data-pulse
networks:
  data-pulse:
volumes:
  db-data-pulse:
