name: Build
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Builder:
    runs-on: node-24-alpine
    defaults:
      run:
        shell: sh
    steps:
      - run: node -v
      - run: ssh -V
